/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { useThree } from "@react-three/fiber";

const Rock = (props) => {
  const { camera } = useThree();
  const { nodes, materials } = useGLTF("/models/rock.glb");
  const mesh = nodes.Rock_LP as Mesh;

  camera.position.setZ(2);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={mesh.geometry}
        material={materials.Rock_LP}
      />
    </group>
  );
};

export default Rock;

useGLTF.preload("/models/rock.glb");
