/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { useThree } from "@react-three/fiber";

const GasGiant = (props) => {
  const { camera } = useThree();
  const { nodes, materials } = useGLTF("/models/gas_giant.glb");
  const meshPlanet = nodes.Sphere_Export as Mesh;
  const meshRing = nodes.Ring_Export as Mesh;

  camera.position.set(-6.171, -0.131, 4.5);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={meshRing.geometry}
        material={materials.ring_export}
        rotation={[0.31, -0.02, 0]}
        scale={0.56}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={meshPlanet.geometry}
        material={materials.gas_giant_export}
        rotation={[0.31, 1.19, -3.14]}
      />
    </group>
  );
};

export default GasGiant;

useGLTF.preload("/models/gas_giant.glb");
